openapi: 3.0.0
info:
  title: Online Shop API
  description: This is a simple online shop built with PHP using the CodeIgniter 4 framework and MySQL.
  version: 1.0.0

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Server error

  /item/create:
    post:
      summary: Add a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '500':
          description: Server error

  /item/update/{id}:
    put:
      summary: Update an existing item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '500':
          description: Server error

  /cart/create:
    post:
      summary: Create a new cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '201':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Server error

  /cart/checkout/{id}:
    put:
      summary: Checkout a cart
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cart checked out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checkout'
        '500':
          description: Server error

  /cart/history/{id}:
    get:
      summary: Get a user's shopping history
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Shopping history retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/History'
        '500':
          description: Server error

  /cartitem/create:
    post:
      summary: Add an item to a cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItem'
      responses:
        '201':
          description: Item added to cart successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        '500':
          description: Server error

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: email
        phone:
          type: string
          pattern: '^[0-9]{10,15}$'
    Item:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
    Cart:
      type: object
      properties:
        user_id:
          type: integer
    CartItem:
      type: object
      properties:
        cart_id:
          type: integer
        item_id:
          type: integer
        quantity:
          type: integer
    Checkout:
      type: object
      properties:
        id:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        total:
          type: number
          format: float
    History:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          items:
            type: array
            items:
              $ref: '#/components/schemas/CartItem'
          total:
            type: number
            format: float
